name: build-test
run-name: ${{ github.actor}} is building test actions
on: [push]
jobs:
  build-and-test-workflows:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
